// ─────────────────────────────────────────────────────────────
// pal-relay — minimal HTTP relay for Gemini calls.
//
// Google's Gemini free tier geo-blocks requests from Render's Frankfurt
// datacenter ("User location is not supported"). This tiny server runs on a
// FREE Render web service in Oregon (a supported US location) and does exactly
// one thing: forward :generateContent POSTs to generativelanguage.googleapis.com.
//
// Pure Node — no dependencies, no npm install, no build. Uses node:http,
// node:crypto and the global fetch (Node 18+).
//
// Security model:
//   - RELAY_TOKEN is generated by Render (generateValue) and shared with the
//     main app via fromService. It never lives in the repo and nobody types it.
//   - The Gemini API key travels in the x-goog-api-key header per request; the
//     relay stores NO secrets and logs NO bodies, tokens or keys.
// ─────────────────────────────────────────────────────────────

import http from "node:http";
import crypto from "node:crypto";

const PORT = process.env.PORT || 10000;
const TOKEN = process.env.RELAY_TOKEN;

if (!TOKEN || TOKEN.length < 20) {
  console.error(
    "RELAY_TOKEN is missing or shorter than 20 characters; refusing to start."
  );
  process.exit(1);
}

const UPSTREAM = "https://generativelanguage.googleapis.com";
const PATH_RE = /^\/v1beta\/models\/[A-Za-z0-9._-]{3,80}:generateContent$/;
const API_KEY_RE = /^[A-Za-z0-9._~-]{20,200}$/;
// Body cap: vision.ts puede enviar hasta 3 imágenes de 5MB cada una, que en
// base64 son ~6,7MB por imagen (~20MB de JSON en el peor caso). 24MB lo cubre
// con margen; con menos, los anuncios de fotos grandes recibirían 413 SOLO en
// producción (en local se va directo a Google, límite 20MB) — un fallo
// difícil de diagnosticar que la sonda gemini-probe no detecta.
const MAX_BODY_BYTES = 24 * 1024 * 1024; // 24MB
const UPSTREAM_TIMEOUT_MS = 90_000;

/** Constant-time token comparison (lengths checked first). */
function tokenMatches(candidate) {
  if (typeof candidate !== "string") return false;
  const a = Buffer.from(candidate);
  const b = Buffer.from(TOKEN);
  if (a.length !== b.length) return false;
  return crypto.timingSafeEqual(a, b);
}

/** Send a response and write the per-request log line (method, path, status
 *  ONLY — never bodies, tokens, keys or query strings; a Google-style
 *  `?key=AIza...` on an unmatched route must NOT end up in Render's logs, so
 *  everything after "?" is dropped and only its presence is marked).
 *  With destroyAfter, the socket is torn down only AFTER the response has been
 *  flushed (an immediate destroy() resets the connection and the client sees
 *  "fetch failed" instead of the status code). */
function finish(req, res, status, body, contentType, destroyAfter) {
  const rawUrl = String(req.url || "");
  const path =
    rawUrl.split("?")[0].slice(0, 120) + (rawUrl.includes("?") ? "?…" : "");
  if (!res.headersSent) {
    const headers = { "content-type": contentType || "text/plain" };
    if (destroyAfter) headers.connection = "close";
    res.writeHead(status, headers);
  }
  if (destroyAfter) {
    res.end(body, () => req.destroy());
  } else {
    res.end(body);
  }
  console.log(`${req.method} ${path} -> ${status}`);
}

/** Read the request body, enforcing the size cap even if content-length lies. */
function readBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    let total = 0;
    req.on("data", (chunk) => {
      total += chunk.length;
      if (total > MAX_BODY_BYTES) {
        reject(new Error("body_too_large"));
        return;
      }
      chunks.push(chunk);
    });
    req.on("end", () => resolve(Buffer.concat(chunks)));
    req.on("error", () => reject(new Error("body_read_error")));
  });
}

async function handle(req, res) {
  const method = req.method || "";
  const path = req.url || "";

  // Health check (Render) + keep-alive pings.
  if (method === "GET" && (path === "/" || path === "/healthz")) {
    return finish(req, res, 200, "ok");
  }

  // Only the exact Gemini generateContent shape is relayed.
  if (!PATH_RE.test(path)) {
    return finish(req, res, 404, "not found");
  }
  if (method !== "POST") {
    return finish(req, res, 405, "method not allowed");
  }

  // Shared-token auth. Never log the token.
  if (!tokenMatches(req.headers["x-relay-token"])) {
    return finish(req, res, 401, "unauthorized");
  }

  // The Gemini key is passed through, never stored or logged.
  const apiKey = req.headers["x-goog-api-key"];
  if (typeof apiKey !== "string" || !API_KEY_RE.test(apiKey)) {
    return finish(req, res, 400, "bad x-goog-api-key");
  }

  // Reject oversized payloads by declared length first…
  const declared = Number(req.headers["content-length"] || "0");
  if (Number.isFinite(declared) && declared > MAX_BODY_BYTES) {
    return finish(req, res, 413, "payload too large", undefined, true);
  }

  // …and again while accumulating chunks (content-length can lie).
  let body;
  try {
    body = await readBody(req);
  } catch (err) {
    if (err && err.message === "body_too_large") {
      return finish(req, res, 413, "payload too large", undefined, true);
    }
    return finish(req, res, 400, "bad request body");
  }

  // Forward to Google as-is and mirror the reply as-is.
  let status;
  let payload;
  try {
    const upstream = await fetch(UPSTREAM + path, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-goog-api-key": apiKey,
      },
      body,
      signal: AbortSignal.timeout(UPSTREAM_TIMEOUT_MS),
    });
    status = upstream.status;
    payload = Buffer.from(await upstream.arrayBuffer());
  } catch {
    return finish(
      req,
      res,
      502,
      JSON.stringify({ error: "upstream_unreachable" }),
      "application/json"
    );
  }
  return finish(req, res, status, payload, "application/json");
}

const server = http.createServer((req, res) => {
  handle(req, res).catch(() => {
    // Unexpected failure: no details leak to the client or the logs.
    try {
      finish(req, res, 500, "internal error");
    } catch {
      /* socket already gone */
    }
  });
});

server.listen(PORT, () => {
  console.log(`pal-relay listening on port ${PORT}`);
});
